name: startertemplate
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  provider: ^6.1.1
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.12
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

  
  uses-material-design: true

 
  assets:
    - lib/images/google.png
    - lib/images/apple.png
    - lib/images/read.png
    - lib/images/think.png
    - lib/images/meditate.png
    - lib/images/tpon.png
    - lib/images/thp.png
    - lib/images/tpoh.png
    - lib/images/lll.png
    - lib/images/happy.png
    - lib/images/dwbh.png
    - lib/images/tfios.png
    - lib/images/all.png
    - lib/images/lib.png
    - lib/images/sl.png
    - lib/images/tgwtdt.png
    - lib/images/rp1.png
    - lib/images/matrix.png
    - lib/images/drive.png
    - lib/images/so.png
    - lib/images/htrj.png
    - lib/images/fc.png
    - lib/images/tgott.png
    - lib/images/ahx.png
    - lib/images/td.png
    - lib/images/kitn.png
    - lib/images/bs.png
    - lib/images/trotd.png
    - lib/images/amour.png
    - lib/images/wgo.png
    - lib/images/nlmg.png
    - lib/images/rfad.png
    - lib/images/jeff.png
    - lib/images/tbs.png
    - lib/images/heat.png
    - lib/images/royals.png
    - lib/images/ofotcn.png
    - lib/images/seven.png
    - lib/images/dwts.png
    - lib/images/mike.png
    - lib/images/astro.png
    - lib/images/nash.png
    - lib/images/racc.png
    - lib/images/bint.png
    - lib/images/beetle.png
    - lib/images/treeball.png
    - lib/images/natheart.png
    - lib/images/logos.png
    

 